function [exp_loss_min, next_sample_point] = min_in_box( objective_fn, prior, evals )
%
% Searches within a prior box.

optim_opts = ...
    optimset('GradObj','off',...
    'Display','off', ...
    'MaxFunEvals', evals,...
    'LargeScale', 'off',...
    'Algorithm','interior-point'...
    );

    
    lower_bound = prior.mean - 3.*sqrt(diag(prior.covariance))';
    upper_bound = prior.mean + 3.*sqrt(diag(prior.covariance))';
    
    
    for i = 1:5
        cur_start_pt = mvnrnd(prior.mean, prior.covariance);
        [next_sample_point, exp_loss_min] = ...
            fmincon(objective_fn,cur_start_pt, ...
            [],[],[],[],...
            lower_bound,upper_bound,[],...
            optim_opts);
    end
end
